version: '3.0'

volumes:
   cgi_volume:
     driver: local
     driver_opts:
       type: ext4
       o: bind
       device: ./srcs/requirements/wordpress/tools/www

   mariadb_volume:
     driver: local
     driver_opts:
       type: ext4
       o: bind
       device: ./srcs/requirements/mariadb/data

networks:
    compose_net:
        driver: bridge

services:
  mariadb:
    build: requirements/mariadb
    networks:
      - compose_net
    expose:
      - "3306"
    command: sh /bin/basic.sh
    volumes:
      - mariadb_volume:/var/lib/mysql

  wordpress:
    build: requirements/wordpress
    networks:
      - compose_net
    expose:
      - "9000"
    command: sh -c "/usr/sbin/php-fpm7 --nodaemonize"
    volumes:
      - cgi_volume:/var/www/html/wordpress
    environment:
      - DB=${DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}


  nginx:
    build: requirements/nginx
    networks:
      - compose_net
    ports:
      - "443:443"
      - "80:80"
    command: bash -c "nginx -g 'daemon off;'"
    volumes:
      - cgi_volume:/var/www/html/wordpress



#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      db:
#        condition: service_started
#
#
#  db:
#    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#
#
#  web:
#    build: timetable
#    command: bash -c "cd web_app/timetable_core && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    ports:
#      - 8000:8000
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - DB_HOST=db
#      - ALGORITHM_HOST=algorithm
#      - ALGORITHM_PORT_OUT=${ALGORITHM_PORT_OUT}
#    depends_on:
#      db:
#        condition: service_started
#      algorithm:
#        condition: service_started
#
#
#  algorithm:
#    build: timetable_algorithm
#    command: bash -c "cd algorithm_app && python -m timetable_genetic_algorithm"
#    volumes:
#      - ./timetable_algorithm/data:/algorithm_app/data
#    ports:
#      - ${ALGORITHM_PORT_OUT}:${ALGORITHM_PORT_IN}
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - DB_HOST=db
#      - WEB_SERVER_HOST=web
#      - EMAIL=${EMAIL}
#      - EMAIL_PASS=${EMAIL_PASS}
#      - ALGORITHM_PORT_IN=${ALGORITHM_PORT_IN}
#      - ALGORITHM_PORT_OUT${ALGORITHM_PORT_OUT}
#    depends_on:
#      db:
#        condition: service_started